Repository notawakestudio/NUSConnect, pull requests merged in 2021-06, with the labels that each got.

#103 Fix jest test warnings and errors
  .eslintrc.js
  .github/workflows/ci.yml
  components/common/Login.tsx
  cypress.json
  cypress/integration/landing_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  setupTests.js
  tests/index.test.js
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#104 Quick fix to remove div in div warning
  pages/dashboard.tsx
Labels: JUST MERGE IT!!!, priority.High

#106 New forum post and firestore connection
  components/common/Auth.tsx
  components/common/Login.tsx
  components/common/Util.ts
  components/forum/ForumAPI.ts
  components/forum/NewPost.tsx
  components/forum/PostListItem.tsx
  components/forum/TextEditor.tsx
  components/quiz/QuizAPI.ts
  components/utils/firebase.ts
  components/utils/users.ts
  package.json
  pages/api/auth/[...nextauth].tsx
  pages/api/userData/index.tsx
  pages/dashboard.tsx
  public/data/ForumData.json
  public/data/ReplyData.json
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#107 Update UI for posts
  .vscode/settings.json
  components/common/NavBar.tsx
  components/forum/ForumAPI.ts
  components/forum/ForumHome.tsx
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostList.tsx
  components/forum/ReplyListItem.tsx
  components/landingPage/Feature.tsx
  pages/forum/[postId].tsx
  pages/quiz/questionMaker.tsx
Labels: JUST MERGE IT!!!, priority.High

#108 Fix quiz creation logic
  components/common/CustomSelect.tsx
  components/quiz/QuizAPI.ts
  components/quiz/QuizList.tsx
  package.json
  pages/quiz/make-question.tsx
  pages/quiz/make-quiz.tsx
  yarn.lock
Labels: JUST MERGE IT!!!, dependencies, priority.High

#109 Update forum CRUD logic
  components/forum/ForumAPI.ts
  components/forum/ForumAPI_MOCK.ts
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  pages/forum/[postId].tsx
  pages/forum/create-post.tsx
  pages/forum/index.tsx
  pages/quiz/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#112 Fix refresh issues
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/quiz/Answer.tsx
  components/quiz/Question.tsx
  package.json
  pages/forum/[postId].tsx
  pages/forum/index.tsx
  pages/quiz/[quizId].tsx
  tailwind.config.js
  yarn.lock
Labels: JUST MERGE IT!!!, dependencies, priority.High

#117 Firebase initial fixes
  components/common/SideBar.tsx
  components/utils/users.ts
  pages/api/auth/[...nextauth].tsx
  pages/dashboard.tsx
  pages/index.tsx
  pages/profile.tsx
Labels: JUST MERGE IT!!!, priority.High

#119 Mobile view, dark mode and UI updates for Forum v1
  components/forum/ForumLayout.tsx
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostList.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyList.tsx
  components/forum/ReplyListItem.tsx
  components/forum/TextContainer.tsx
  pages/forum/[postId].tsx
  pages/forum/create-post.tsx
Labels: JUST MERGE IT!!!, priority.High

#120 Fix exp error
  pages/dashboard.tsx
Labels: JUST MERGE IT!!!, type.Bug

#121 Fixed responsive issues with navbar and forum
  .vscode/settings.json
  components/common/NavBar.tsx
  components/common/QuickLink.tsx
  components/common/Search.tsx
  components/common/Util.ts
  components/forum/ForumLayout.tsx
  components/forum/PostList.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/forum/TextContainer.tsx
  tailwind.config.js
  tests/index.test.js
Labels: JUST MERGE IT!!!, priority.High

#122 Add toastify and minor quiz style update
  components/quiz/Answer.tsx
  components/quiz/Question.tsx
  package.json
  pages/_app.tsx
  yarn.lock
Labels: JUST MERGE IT!!!, dependencies, priority.Medium

#125 Nav bar responsive update
  components/common/NavBar.tsx
  components/common/QuickLink.tsx
  components/forum/PostListItem.tsx
  components/forum/ReplyList.tsx
Labels: JUST MERGE IT!!!, priority.High

#126 Move navbar to root
  components/common/Layout.tsx
  components/common/NavBar.tsx
  components/forum/ForumLayout.tsx
  package.json
  pages/_app.tsx
  pages/dashboard.tsx
  pages/index.tsx
  pages/quiz/[quizId].tsx
  pages/quiz/index.tsx
  public/white_profile-placeholder.png
  tailwind.config.js
  tests/index.test.js
  yarn.lock
Labels: JUST MERGE IT!!!, dependencies, priority.High

#127 Minor UI fixes
  components/common/Footer.tsx
  components/common/Login.tsx
  components/common/NavBar.tsx
  components/common/QuickLink.tsx
  pages/dashboard.tsx
Labels: JUST MERGE IT!!!, priority.High

#130 Changes to navbar and some more UI updates
  components/common/Layout.tsx
  components/common/NavBar.tsx
  components/forum/ForumHome.tsx
  components/forum/ForumLayout.tsx
  components/forum/PostMain.tsx
  package.json
  pages/_app.tsx
  pages/forum/[postId].tsx
  tailwind.config.js
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#131 Update Forum & others
  components/common/NavBar.tsx
  components/common/QuickLink.tsx
  components/forum/ForumAPI.ts
  components/forum/NewReply.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/module/ModuleAPI.ts
  components/utils/store.tsx
  pages/_app.tsx
  pages/forum/[postId].tsx
  pages/forum/create-post.tsx
  pages/forum/index.tsx
  pages/login.tsx
  pages/module/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#132 Update forum date and some quiz ui
  components/common/NavBar.tsx
  components/common/Search.tsx
  components/common/Util.ts
  components/forum/PostList.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/quiz/QuizItem.tsx
  components/quiz/QuizList.tsx
  pages/quiz/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#134 Quiz logic updates and UI changes initial ver
  components/common/CustomMultiSelect.tsx
  components/common/CustomSingleSelect.tsx
  components/common/TextContainer.tsx
  components/forum/ForumHome.tsx
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/quiz/QuizAPI.ts
  pages/quiz/make-question.tsx
  pages/quiz/make-quiz.tsx
Labels: JUST MERGE IT!!!, priority.High

#136 Add delete ability
  components/forum/ForumAPI.ts
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  pages/forum/create-post.tsx
Labels: priority.High

#138 Add swr
  components/forum/ForumAPI.ts
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostList.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/store/forum.tsx
  package.json
  pages/forum/[postId].tsx
  pages/forum/create-post.tsx
  pages/forum/index.tsx
  yarn.lock
Labels: JUST MERGE IT!!!, dependencies, priority.High

#141 Update some swr and fetching methods
  components/common/Footer.tsx
  components/forum/ForumAPI.ts
  components/forum/ForumHome.tsx
  components/forum/ForumLayout.tsx
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostMain.tsx
  pages/forum/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#142 Many updates
  components/common/CustomSingleSelect.tsx
  components/common/Footer.tsx
  components/common/Layout.tsx
  components/common/NavigationDrawer.tsx
  components/common/SideBar.tsx
  components/common/SidebarLayout.tsx
  components/common/TextContainer.tsx
  components/forum/ForumAPI.ts
  components/forum/ForumHome.tsx
  components/forum/NewPost.tsx
  components/forum/PostList.tsx
  components/profile/Badges.tsx
  components/profile/ModuleCards.tsx
  components/profile/ProfileHeader.tsx
  components/quiz/Question.tsx
  components/quiz/QuizItem.tsx
  components/quiz/QuizList.tsx
  pages/dashboard.tsx
  pages/forum/index.tsx
  pages/profile.tsx
  pages/profile/badges.tsx
  pages/profile/index.tsx
  pages/quiz/[quizId].tsx
  pages/quiz/index.tsx
  pages/quiz/make-question.tsx
  public/data/IndividualModuleData.json
Labels: JUST MERGE IT!!!, priority.High

#143 Forum update
  components/common/Footer.tsx
  components/common/Search.tsx
  components/common/TagBar.tsx
  components/forum/ForumAPI.ts
  components/forum/ForumLayout.tsx
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostList.tsx
  components/forum/PostMain.tsx
  components/quiz/QuizList.tsx
  pages/_app.tsx
  pages/forum/[postId].tsx
  pages/forum/create-post.tsx
  pages/forum/index.tsx
  pages/scoreboard.tsx
Labels: JUST MERGE IT!!!, priority.High

#145 Fix tailwind config
  components/common/CustomSingleSelect.tsx
  components/quiz/Question.tsx
  pages/quiz/make-question.tsx
  pages/quiz/make-quiz.tsx
  tailwind.config.js
Labels: JUST MERGE IT!!!, priority.High

#149 Update Eslint and forum post - question
  .eslintrc.js
  components/common/Auth.tsx
  components/common/CustomMultiSelect.tsx
  components/common/CustomSingleSelect.tsx
  components/common/Layout.tsx
  components/common/NavBar.tsx
  components/common/NavigationDrawer.tsx
  components/common/Pagination.tsx
  components/common/SidebarLayout.tsx
  components/common/TagBar.tsx
  components/common/Util.ts
  components/forum/ForumAPI.ts
  components/forum/ForumLayout.tsx
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/quiz/Question.tsx
  components/quiz/QuizAPI.ts
  package.json
  pages/api/auth/[...nextauth].tsx
  pages/dashboard.tsx
  pages/forum/[postId].tsx
  pages/profile/badges.tsx
  pages/profile/index.tsx
  pages/scoreboard.tsx
  yarn.lock
Labels: JUST MERGE IT!!!, dependencies, priority.High

#151 Include user data into backend
  components/common/NavBar.tsx
  components/profile/ProfileHeader.tsx
  components/profile/UserAPI.ts
  components/store/user.tsx
  components/utils/users.ts
  pages/_app.tsx
Labels: JUST MERGE IT!!!, priority.High

#152 Bug fixes and minor adjustments
  components/common/NavBar.tsx
  components/common/NavigationDrawer.tsx
  components/common/SideBar.tsx
  components/profile/Badges.tsx
  components/profile/ProfileHeader.tsx
  pages/dashboard.tsx
  pages/profile/badges.tsx
  pages/scoreboard.tsx
Labels: JUST MERGE IT!!!, priority.High

#154 Add tests & coverage tools
  .babelrc
  .gitignore
  cypress/fixtures/example.json
  cypress/integration/dashboard_spec.ts
  cypress/integration/forum_spec.ts
  cypress/integration/landing_spec.ts
  cypress/integration/login_spec.ts
  cypress/integration/profile_spec.ts
  cypress/integration/quiz_spec.ts
  cypress/plugins/index.js
  cypress/support/index.js
  cypress/tsconfig.json
  package.json
  tsconfig.json
  yarn.lock
Labels: JUST MERGE IT!!!, dependencies, priority.High

#155 Bug fix and update forum
  components/common/LikeButton.tsx
  components/forum/ForumAPI.ts
  components/forum/ModelQuestionCard.tsx
  components/forum/PostMain.tsx
  components/quiz/QuizAPI.ts
  pages/forum/[postId].tsx
Labels: JUST MERGE IT!!!, priority.High

#156 Quiz UI updates and make quiz bug fix
  components/common/CustomSingleSelect.tsx
  components/common/Pagination.tsx
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/ReplyListItem.tsx
  components/profile/ProfileHeader.tsx
  components/quiz/Answer.tsx
  components/quiz/OptionsBar.tsx
  components/quiz/Question.tsx
  components/quiz/QuizAPI.ts
  components/quiz/QuizItemCard.tsx
  components/quiz/QuizList.tsx
  components/quiz/RelatedPosts.tsx
  components/quiz/ScoreCard.tsx
  components/quiz/types.ts
  package.json
  pages/_app.tsx
  pages/forum/create-post.tsx
  pages/module/index.tsx
  pages/quiz/[quizId].tsx
  pages/quiz/index.tsx
  pages/quiz/make-question.tsx
  pages/quiz/make-quiz.tsx
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#161 UI updates for post main and new post
  components/common/LikeButton.tsx
  components/forum/ForumAPI.ts
  components/forum/ModelQuestionCard.tsx
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/quiz/OptionsBar.tsx
  components/quiz/Question.tsx
  components/quiz/QuizAPI.ts
  components/quiz/RelatedPosts.tsx
  components/quiz/types.ts
  pages/forum/[postId].tsx
  pages/forum/create-post.tsx
  pages/quiz/[quizId].tsx
Labels: JUST MERGE IT!!!, priority.High

#162 bug fix and dependency upgrade
  package.json
  pages/forum/[postId].tsx
  yarn.lock
Labels: JUST MERGE IT!!!, dependencies, priority.High

#166 Add test
  components/forum/PostList.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  cypress.json
  cypress/integration/forum/forum_spec.ts
  cypress/integration/forum_spec.ts
Labels: JUST MERGE IT!!!, priority.High

#167 Add test (Login Mock)
  .gitignore
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  cypress/integration/forum/forum_spec.ts
  cypress/support/commands.js
  cypress/support/commands.ts
  cypress/support/index.d.ts
  cypress/support/index.ts
Labels: JUST MERGE IT!!!, priority.High

#168 Test & post -> quiz feature
  components/common/Auth.tsx
  components/common/TagBar.tsx
  components/forum/ForumAPI.ts
  components/forum/ForumHome.tsx
  components/forum/NewPost.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyList.tsx
  components/forum/ReplyListItem.tsx
  components/landingPage/Hero.tsx
  components/landingPage/Pricing.tsx
  components/module/ModuleAPI.ts
  components/profile/ModuleCards.tsx
  components/quiz/OptionsBar.tsx
  components/quiz/QuizAPI.ts
  cypress/integration/forum/forum_spec.ts
  cypress/support/commands.ts
  pages/404.tsx
  pages/_app.tsx
  pages/api/hello.js
  pages/forum/[postId].tsx
  pages/forum/create-post.tsx
  pages/forum/index.tsx
  pages/quiz/[quizId].tsx
  pages/quiz/make-question/[postId].tsx
  pages/quiz/make-question/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#174 Minor update to quiz creation toast
  pages/quiz/make-question/[postId].tsx
  pages/quiz/make-question/index.tsx
  pages/quiz/make-quiz.tsx
Labels: JUST MERGE IT!!!, priority.High

#178 Finish E2E tests for milestone 2
  components/common/NavigationDrawer.tsx
  components/common/SideBar.tsx
  components/common/TagBar.tsx
  components/common/Util.ts
  components/forum/ForumAPI.ts
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/inbox/MessageSection.tsx
  components/profile/DisplayName.tsx
  components/profile/UserAPI.ts
  components/quiz/QuizItemCard.tsx
  cypress/integration/quiz/makeQuestion_spec.ts
  cypress/integration/quiz/makeQuiz_spec.ts
  cypress/integration/quiz/quiz_spec.ts
  cypress/integration/quiz_spec.ts
  pages/dashboard.tsx
  pages/profile/inbox.tsx
  pages/quiz/[quizId].tsx
Labels: JUST MERGE IT!!!, priority.High

#180 add type to message
  components/common/Util.ts
  components/inbox/MessageSection.tsx
  components/profile/UserAPI.ts
  pages/dashboard.tsx
Labels: JUST MERGE IT!!!, priority.High

#183 Fix bug
  components/forum/NewPost.tsx
  pages/quiz/make-quiz.tsx
Labels: JUST MERGE IT!!!, priority.High

#184 Fix account login issue and minor update to module integration
  components/profile/UserAPI.ts
  pages/api/auth/[...nextauth].tsx
Labels: JUST MERGE IT!!!, priority.High, type.Bug

#185 Quick fix dashboard
  public/data/ModuleDataNew.json
Labels: JUST MERGE IT!!!, priority.High

#187 Clear comment/post input after submit
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  pages/forum/create-post.tsx
Labels: JUST MERGE IT!!!, priority.High

#189 Quiz UI update
  components/common/Search.tsx
  components/quiz/QuizItemCard.tsx
  components/quiz/QuizList.tsx
  cypress/integration/quiz/quiz_spec.ts
  pages/quiz/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#190 Fix inbox
  components/profile/UserAPI.ts
Labels: JUST MERGE IT!!!, type.Bug

#192 Update quiz userId issue
  components/profile/Avatar.tsx
  components/quiz/QuizItemCard.tsx
  components/quiz/QuizList.tsx
  pages/quiz/make-quiz.tsx
Labels: JUST MERGE IT!!!, priority.High

#195 Fix badges page UI & Scoreboard
  components/profile/Badges.tsx
  components/profile/UserAPI.ts
  components/store/user.tsx
  pages/profile/badges.tsx
  pages/scoreboard.tsx
Labels: JUST MERGE IT!!!, priority.Medium
