Repository notawakestudio/NUSConnect, pull requests merged in 2021-07, with the labels that each got.

#198 bug fix, quiz and question ui updates logic improvements
  components/common/Search.tsx
  components/dashboard/NewAnnouncement.tsx
  components/forms/CustomMultiSelect.tsx
  components/forms/CustomSingleSelect.tsx
  components/forms/Required.tsx
  components/forms/TagMultiSelect.tsx
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/quiz/OptionsBar.tsx
  components/quiz/QuizAPI.ts
  components/quiz/QuizList.tsx
  cypress/integration/quiz/makeQuiz_spec.ts
  pages/quiz/make-question/[postId].tsx
  pages/quiz/make-question/index.tsx
  pages/quiz/make-quiz.tsx
Labels: JUST MERGE IT!!!, priority.High

#199 very minor fixes
  components/inbox/MessageSection.tsx
  components/profile/UserAPI.ts
  pages/dashboard/index.tsx
  pages/scoreboard.tsx
Labels: JUST MERGE IT!!!, priority.High

#200 Bug fixes, and refactoring of code
  components/common/NavigationDrawer.tsx
  components/common/Search.tsx
  components/common/SideBar.tsx
  components/dashboard/AnnouncementItem.tsx
  components/forum/ForumAPI.ts
  components/forum/ForumLayout.tsx
  components/forum/NewPost.tsx
  components/layouts/Layout.tsx
  components/layouts/NavigationDrawer.tsx
  components/layouts/SideBar.tsx
  components/layouts/SidebarBody.tsx
  components/layouts/SidebarHeader.tsx
  components/layouts/SidebarLayout.tsx
  components/profile/ProfileHeader.tsx
  components/quiz/QuizItemCard.tsx
  components/quiz/QuizList.tsx
  cypress/integration/forum/forum_spec.ts
  pages/dashboard/index.tsx
  pages/login.tsx
  pages/maker.tsx
  pages/module/create-module.tsx
  pages/module/index.tsx
  pages/module/new-announcement.tsx
  pages/module/new-quest.tsx
  pages/profile/badges.tsx
  pages/profile/inbox.tsx
  pages/profile/index.tsx
  pages/quiz/collate.tsx
  pages/quiz/index.tsx
  pages/quiz/make-question/[postId].tsx
  pages/quiz/make-question/index.tsx
  pages/quiz/make-quiz.tsx
  pages/quiz/make.tsx
  pages/scoreboard.tsx
Labels: JUST MERGE IT!!!, priority.High

#201 Fixed bug for linked question
  components/forms/CustomSingleSelect.tsx
  components/forum/NewPost.tsx
Labels: JUST MERGE IT!!!, priority.High

#205 recover tests for forum
  cypress/integration/forum/forum_spec.ts
Labels: JUST MERGE IT!!!, priority.High

#207 Major update on module related stuff
  components/dashboard/Announcement.tsx
  components/dashboard/DashboardAPI.ts
  components/layouts/SidebarBody.tsx
  components/layouts/SidebarHeader.tsx
  components/module/AnnouncementItem.tsx
  components/module/ModuleAPI.ts
  components/module/NewAnnouncement.tsx
  components/module/NewQuest.tsx
  components/module/QuestItem.tsx
  components/profile/ModuleCards.tsx
  components/profile/UserAPI.ts
  components/quiz/QuizItem.tsx
  pages/dashboard/index.tsx
  pages/module/index.tsx
  pages/module/new-announcement.tsx
  pages/module/new-module.tsx
  pages/module/new-quest.tsx
  public/data/IndividualModuleData.json
  public/data/ModuleData.json
  public/data/ModuleDataNew.json
Labels: JUST MERGE IT!!!, priority.High

#213 Update announcement and module data refactor
  components/module/AnnouncementItem.tsx
  components/module/ModuleAPI.ts
  components/module/NewAnnouncement.tsx
  components/module/NewQuest.tsx
  components/store/user.tsx
  pages/dashboard/index.tsx
  pages/module/new-module.tsx
  public/data/ModuleData.json
Labels: JUST MERGE IT!!!, priority.High

#216 Join module functionality
  components/module/ModuleAPI.ts
  components/profile/UserAPI.ts
  pages/module/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#217 Quest and announcement updates
  components/common/Util.ts
  components/forms/DatePickerField.tsx
  components/forum/ForumAPI.ts
  components/forum/ForumAPI_MOCK.ts
  components/module/ModuleAPI.ts
  components/module/NewQuest.tsx
  components/module/QuestItem.tsx
  components/quiz/NewQuestion.tsx
  package.json
  pages/dashboard/index.tsx
  pages/module/new-quest.tsx
  pages/quiz/make-question/index.tsx
  tsconfig.json
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#218 Added created date for quest creation
  components/module/ModuleAPI.ts
  components/module/NewQuest.tsx
Labels: JUST MERGE IT!!!, priority.High

#219 Fix backend for quests
  components/module/ModuleAPI.ts
  components/module/NewQuest.tsx
  components/module/QuestItem.tsx
Labels: JUST MERGE IT!!!, priority.High

#221 Fix errors with date and form for quest creation
  components/forms/DatePickerField.tsx
  components/module/ModuleAPI.ts
  components/module/NewQuest.tsx
  components/module/QuestItem.tsx
Labels: JUST MERGE IT!!!, priority.High

#222 Fix redirect url
  components/common/Login.tsx
Labels: JUST MERGE IT!!!, priority.High

#223 Fix bugs for dashboard
  components/module/NewAnnouncement.tsx
  pages/dashboard/index.tsx
  pages/module/new-announcement.tsx
Labels: JUST MERGE IT!!!, priority.High, type.Bug

#224 Fix badges & quiz sort/search & user roles
  components/forum/ForumLayout.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/profile/Badges.tsx
  components/profile/UserAPI.ts
  components/quiz/QuizAPI.ts
  components/quiz/QuizList.tsx
  pages/dashboard/index.tsx
  pages/module/index.tsx
  pages/module/new-announcement.tsx
  pages/module/new-module.tsx
  pages/module/new-quest.tsx
  pages/profile/badges.tsx
  pages/quiz/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#230 Update quiz like functionality
  components/quiz/QuizAPI.ts
  components/quiz/QuizItemCard.tsx
  components/quiz/QuizList.tsx
  components/quiz/types.ts
  pages/dashboard/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#231 Forum UI update and some refactoring
  components/common/Search.tsx
  components/common/TagBar.tsx
  components/common/TextContainer.tsx
  components/forum/ForumLayout.tsx
  components/forum/NewReply.tsx
  components/forum/PostList.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyList.tsx
  components/forum/ReplyListItem.tsx
  components/layouts/NavigationDrawer.tsx
  components/layouts/SideBar.tsx
  components/layouts/SidebarBody.tsx
  components/layouts/SidebarItem.tsx
  components/layouts/SidebarLayout.tsx
  cypress/integration/forum/forum_spec.ts
  pages/_app.tsx
  pages/forum/[postId].tsx
  pages/forum/create-post.tsx
  pages/forum/index.tsx
  public/data/ModuleData.json
  tsconfig.json
Labels: JUST MERGE IT!!!, priority.High

#237 new question type "written", forum layout improvements, sidebar abstracted
  components/common/NavBar.tsx
  components/common/Search.tsx
  components/common/TagBar.tsx
  components/forum/ForumLayout.tsx
  components/forum/NewReply.tsx
  components/forum/PostList.tsx
  components/layouts/NavigationDrawer.tsx
  components/layouts/SideBar.tsx
  components/layouts/SidebarBody.tsx
  components/layouts/SidebarLayout.tsx
  components/quiz/Answer.tsx
  components/quiz/NewQuestion.tsx
  components/quiz/Question.tsx
  components/quiz/QuizAPI.ts
  components/quiz/QuizList.tsx
  components/quiz/types.ts
  pages/404.tsx
  pages/_app.tsx
  pages/dashboard/index.tsx
  pages/forum/[postId].tsx
  pages/forum/index.tsx
  pages/module/index.tsx
  pages/module/new-announcement.tsx
  pages/module/new-quest.tsx
  pages/profile/badges.tsx
  pages/profile/inbox.tsx
  pages/profile/index.tsx
  pages/quiz/[quizId].tsx
  pages/quiz/index.tsx
  pages/quiz/make-question/index.tsx
  pages/quiz/make-quiz.tsx
  pages/scoreboard.tsx
  styles/globals.css
Labels: JUST MERGE IT!!!, priority.High

#240 Fix landing and 404 page
  pages/404.tsx
  pages/_app.tsx
  public/peekCat.jpg
Labels: JUST MERGE IT!!!, priority.High

#242 Fix E2E tests and minor UI touchup
  components/profile/Badges.tsx
  cypress.json
  cypress/integration/badges_spec.ts
  cypress/integration/error_spec.ts
  cypress/integration/inbox_spec.ts
  cypress/integration/module_spec.ts
  cypress/integration/scoreboard_spec.ts
  pages/_app.tsx
  pages/profile/inbox.tsx
Labels: JUST MERGE IT!!!, priority.High

#243 Add Unit tests to cover utility methods and component checking
  components/common/Util.ts
  components/layouts/SidebarBody.tsx
  components/profile/Badges.tsx
  components/profile/UserAPI.ts
  cypress/integration/scoreboard_spec.ts
  pages/profile/badges.tsx
  pages/profile/scoreboard.tsx
  tests/index.test.js
  tests/util.test.js
Labels: JUST MERGE IT!!!, priority.High

#247 Fix forum home page
  components/forum/ForumHome.tsx
  public/markdown.png
Labels: JUST MERGE IT!!!, priority.High

#248 Integrated quiz taking, layout fix
  components/layouts/SidebarLayout.tsx
  components/quiz/AnswerObject.ts
  components/quiz/NewQuestion.tsx
  components/quiz/NewQuiz.tsx
  components/quiz/Question.tsx
  components/quiz/QuizAPI.ts
  pages/dashboard/index.tsx
  pages/quiz/[quizId].tsx
  pages/quiz/collate.tsx
  pages/quiz/make-question/[postId].tsx
  pages/quiz/make-question/index.tsx
  pages/quiz/make-quiz.tsx
  pages/quiz/make.tsx
Labels: JUST MERGE IT!!!, priority.High

#249 Dependency clean up and Quiz update to CRUD from module
  components/common/MDEditor.tsx
  components/common/NavBar.tsx
  components/common/Util.ts
  components/forum/NewPost.tsx
  components/module/ModuleAPI.ts
  components/profile/Badges.tsx
  components/profile/ModuleCards.tsx
  components/profile/ProfileHeader.tsx
  components/quiz/NewQuestion.tsx
  components/quiz/NewQuiz.tsx
  components/quiz/QuizAPI.ts
  components/quiz/QuizItemCard.tsx
  components/store/module.tsx
  package.json
  pages/dashboard/index.tsx
  pages/maker.tsx
  pages/profile/scoreboard.tsx
  pages/quiz/index.tsx
  pages/quiz/make-quiz.tsx
  yarn.lock
Labels: JUST MERGE IT!!!, dependencies, priority.High

#251 Switch forum to module based
  components/forum/ForumAPI.ts
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/quiz/QuizAPI.ts
  components/quiz/QuizItemCard.tsx
Labels: JUST MERGE IT!!!, priority.High

#252 Fix week number type
  components/forum/ForumAPI.ts
  components/forum/NewPost.tsx
  components/forum/ReplyListItem.tsx
Labels: JUST MERGE IT!!!, priority.High

#253 Fix module switching issues
  components/common/NavBar.tsx
  components/store/localStorage.tsx
  components/store/module.tsx
  pages/dashboard/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#255 Fix quest update
  components/common/Util.ts
  components/forum/ForumAPI.ts
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/module/ModuleAPI.ts
  components/module/NewQuest.tsx
  components/profile/Badges.tsx
  components/profile/ProfileHeader.tsx
  components/profile/UserAPI.ts
  components/store/localStorage.tsx
  pages/dashboard/index.tsx
  pages/module/index.tsx
  pages/module/new-quest.tsx
  pages/quiz/[quizId].tsx
Labels: JUST MERGE IT!!!, priority.High

#254 Dashboard update and other small functional updates
  components/common/Login.tsx
  components/common/NavBar.tsx
  components/common/Util.ts
  components/forum/NewPost.tsx
  components/forum/PostList.tsx
  components/landingPage/Feature.tsx
  components/landingPage/Hero.tsx
  components/landingPage/Team.tsx
  components/landingPage/Timeline.tsx
  components/quiz/QuizList.tsx
  pages/index.tsx
  public/NUSConnectBanner.svg
  public/favicon.ico
  tests/index.test.js
Labels: JUST MERGE IT!!!, priority.High

#258 Fix multiple question quiz creation
  components/quiz/NewQuiz.tsx
  components/quiz/QuizAPI.ts
Labels: JUST MERGE IT!!!, priority.High

#261 Fix week issue
  components/common/Util.ts
  components/forum/PostList.tsx
Labels: priority.High

#265 dark mode fixes
  components/common/NavBar.tsx
  components/inbox/MessageSection.tsx
  components/profile/Badges.tsx
  components/quiz/QuizItemCard.tsx
  pages/dashboard/index.tsx
  pages/profile/badges.tsx
  pages/profile/inbox.tsx
  pages/profile/scoreboard.tsx
  pages/quiz/[quizId].tsx
Labels: priority.High

#267 make content compulsory (bug fix)
  components/forum/ForumAPI.ts
  components/forum/NewPost.tsx
  components/forum/PostList.tsx
  components/module/ModuleAPI.ts
  components/module/NewAnnouncement.tsx
  components/module/QuestItem.tsx
  components/quiz/NewQuiz.tsx
  components/quiz/QuizAPI.ts
Labels: JUST MERGE IT!!!, priority.High, type.Bug

#270 Forum cleanup
  components/forum/ForumAPI.ts
  components/forum/ForumAPI_MOCK.ts
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/forum/PostMain.tsx
  components/forum/ReplyListItem.tsx
  components/profile/Badges.tsx
  pages/module/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#273 Include details on quest completion status
  components/module/QuestItem.tsx
  pages/dashboard/index.tsx
Labels: priority.High

#276 Fix announcement
  components/module/NewAnnouncement.tsx
  components/profile/UserAPI.ts
  cypress/integration/quiz/quiz_spec.ts
Labels: priority.High

#277 Add more badges and minor fixes
  components/common/Util.ts
  components/forum/NewPost.tsx
  components/forum/NewReply.tsx
  components/profile/Badges.tsx
  components/profile/UserAPI.ts
  components/quiz/QuizItemCard.tsx
  pages/quiz/[quizId].tsx
Labels: priority.High
