Repository notawakestudio/NUSConnect, pull requests merged in 2021-05, with the labels that each got.

#18 Relevant info on documentations
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Testing.md
  docs/UserGuide.md
  docs/workflow.md
Labels: priority.High

#19 Add index page
  docs/index.md
Labels: priority.High

#20 Minor update
  docs/Configuration.md
  docs/ConfigurationGuide.md
  docs/DevOps.md
  docs/DevOpsGuide.md
  docs/DeveloperGuide.md
  docs/TestingGuide.md
  docs/UserGuide.md
  docs/WorkflowGuide.md
  docs/_config.yml
  docs/index.md
Labels: priority.High

#21 Major first draft fix
  docs/ConfigurationGuide.md
  docs/DevOpsGuide.md
  docs/DeveloperGuide.md
  docs/TestingGuide.md
  docs/Timeline.md
  docs/UserGuide.md
  docs/WorkflowGuide.md
  docs/_config.yml
  docs/index.md
Labels: priority.High

#22 Finish first draft of docs
  docs/ConfigurationGuide.md
  docs/DeveloperGuide.md
  docs/Timeline.md
  docs/UserGuide.md
  docs/_config.yml
  docs/index.md
Labels: priority.High

#23 Bug fix index links
  docs/index.md
Labels: priority.High

#24 Add basic quiz logic
  .eslintrc.js
  components/Header.tsx
  components/common/Util.ts
  components/quiz/API.ts
  components/quiz/Answer.tsx
  components/quiz/QuestionCard.tsx
  docs/DeveloperGuide.md
  pages/index.tsx
  pages/quiz.tsx
  public/data.json
  tailwind.config.js
Labels: priority.High

#26 Add some components
  components/common/Footer.tsx
  components/common/NavBar.tsx
  components/common/Search.tsx
  pages/index.tsx
  pages/quiz_all.tsx
Labels: priority.High

#27 Update quiz list
  components/common/Footer.tsx
  components/common/NavBar.tsx
  components/common/Search.tsx
  components/common/SideBar.tsx
  components/quiz/QuizList.tsx
  components/quiz/QuizListItem.tsx
  pages/index.tsx
  pages/quiz_all.tsx
  tailwind.config.js
Labels: priority.High

#28 More updates on basic layout
  components/common/Footer.tsx
  components/common/NavBar.tsx
  components/common/Pagination.tsx
  components/common/Search.tsx
  components/quiz/QuestionItem.tsx
  components/quiz/QuizList.tsx
  components/quiz/QuizListItem.tsx
  pages/404.tsx
  pages/index.tsx
  pages/quiz.tsx
Labels: priority.High

#29 Update quiz names and started working on forum
  components/forum/ForumAPI.ts
  components/forum/Post.tsx
  components/forum/PostList.tsx
  components/quiz/QuizAPI.ts
  docs/DeveloperGuide.md
  pages/forum.tsx
  pages/quiz.tsx
  public/data/ForumData.json
  public/data/QuizData.json
Labels: JUST MERGE IT!!!, priority.High

#30 Quick fix and minor config edits
  components/forum/PostList.tsx
  next.config.js
  tailwind.config.js
Labels: priority.High

#31 Update quiz route and quiz mock data
  components/common/Pagination.tsx
  components/quiz/Answer.tsx
  components/quiz/QuestionItem.tsx
  components/quiz/QuizAPI.ts
  components/quiz/QuizList.tsx
  components/quiz/QuizListItem.tsx
  package.json
  pages/404.tsx
  pages/index.tsx
  pages/quiz.tsx
  pages/quiz_all.tsx
  pages/quizzes/[quizId].tsx
  public/data/QuestionBank.json
  public/data/QuizData.json
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#32 Minor typo fix
  components/quiz/QuizAPI.ts
  components/quiz/QuizList.tsx
Labels: JUST MERGE IT!!!, priority.High

#33 Yong
  README.md
  components/common/Footer.tsx
  components/common/NavBar.tsx
  components/common/Pagination.tsx
  components/common/QuickLink.tsx
  components/common/Search.tsx
  components/dashboard/ModuleAPI.ts
  components/landingPage/Hero.tsx
  components/landingPage/Pricing.tsx
  components/landingPage/Team.tsx
  components/quiz/QuestionItem.tsx
  components/quiz/QuizAPI.ts
  docs/_config.yml
  package.json
  pages/404.tsx
  pages/dashboard.tsx
  pages/index.tsx
  pages/quiz.tsx
  pages/quizzes/[quizId].tsx
  public/data/ModuleData.json
  public/data/ProfileData.json
  public/data/QuizData.json
  styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#34 Fix quiz logic
  components/common/QuickLink.tsx
  components/quiz/Answer.tsx
  components/quiz/QuestionItem.tsx
  components/quiz/QuizAPI.ts
  pages/quizzes/[quizId].tsx
Labels: JUST MERGE IT!!!, priority.High

#35 Minor styling of dashboard
  components/common/Editor.tsx
  components/common/Footer.tsx
  components/common/Layout.tsx
  components/common/NavBar.tsx
  components/common/QuickLink.tsx
  components/common/SideBar.tsx
  components/common/SideBarA.tsx
  components/common/Util.ts
  components/quiz/QuestionItem.tsx
  components/quiz/QuizListItem.tsx
  package.json
  pages/dashboard.tsx
  pages/maker.tsx
  pages/quizzes/[quizId].tsx
  public/data/QuestionBank.json
  public/data/QuizData.json
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#39 Add github action
  .github/workflows/ci.yml
  components/common/Editor.tsx
  docs/ConfigurationGuide.md
  docs/DevOpsGuide.md
Labels: JUST MERGE IT!!!, priority.High

#46 Updates Quiz List Item
  components/quiz/QuizListItem.tsx
  public/data/QuizData.json
Labels: JUST MERGE IT!!!, priority.Medium

#47 Documentation update 1
  .github/workflows/ci.yml
  docs/ConfigurationGuide.md
  docs/DevOpsGuide.md
  docs/DeveloperGuide.md
  docs/TestingGuide.md
  docs/Timeline.md
  docs/UserGuide.md
  docs/WorkflowGuide.md
  jest.config.js
  setupTests.js
  tests/index.test.js
Labels: JUST MERGE IT!!!, priority.High

#52 Add feature to landing page
  components/landingPage/Feature.tsx
  components/landingPage/Pricing.tsx
  components/landingPage/Team.tsx
  pages/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#54 Fix UI bugs
  components/common/NavBar.tsx
  components/forum/Post.tsx
  components/forum/PostList.tsx
  components/forum/PostMainItem.tsx
  docs/Timeline.md
  pages/forum.tsx
  pages/forum/[id]/index.tsx
  pages/index.tsx
Labels: priority.High, type.Task

#55 Add editor demo
  components/common/Editor.tsx
  components/quiz/QuizListItem.tsx
  package.json
  pages/index.tsx
  pages/maker.tsx
  pages/quiz/[quizId].tsx
  styles/globals.css
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#59 Add Markdown editor & Other Wk2 sprint tasks
  .prettierrc.js
  components/common/Alert.tsx
  components/common/Editor.tsx
  components/common/MDEditor.tsx
  components/common/Util.ts
  components/quiz/Answer.tsx
  components/quiz/Question.tsx
  components/quiz/QuestionItem.tsx
  components/quiz/QuizAPI.ts
  components/quiz/QuizItem.tsx
  components/quiz/QuizList.tsx
  components/quiz/ScoreCard.tsx
  components/quiz/types.ts
  docs/DeveloperGuide.md
  docs/UserGuide.md
  package.json
  pages/maker.tsx
  pages/quiz.tsx
  pages/quiz/[quizId].tsx
  pages/quiz/collate.tsx
  pages/quiz/index.tsx
  pages/quiz/make.tsx
  public/data/QuestionBank.json
  public/data/QuestionFormat.json
  public/data/QuestionFormat.yaml
  public/data/QuizData.json
  public/data/QuizFormat.yaml
  styles/globals.css
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#62 Add quiz review mode
  components/quiz/Answer.tsx
  components/quiz/AnswerObject.ts
  components/quiz/Question.tsx
  components/quiz/ScoreCard.tsx
  components/quiz/types.ts
  docs/DeveloperGuide.md
  pages/quiz/[quizId].tsx
Labels: JUST MERGE IT!!!, priority.High

#63 Add login and auth
  .gitignore
  .vscode/settings.json
  docs/DeveloperGuide.md
  package.json
  pages/_app.js
  pages/api/auth/[...nextauth].tsx
  pages/api/userData/index.tsx
  pages/dashboard.tsx
  pages/index.tsx
  pages/login.tsx
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#70 Add data to dashboard
  components/common/Auth.tsx
  components/common/Footer.tsx
  components/common/NavBar.tsx
  components/forum/PostList.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMainItem.tsx
  components/landingPage/Team.tsx
  pages/api/userData/index.tsx
  pages/dashboard.tsx
  pages/forum.tsx
  pages/forum/[forumId].tsx
  pages/forum/index.tsx
  pages/login.tsx
Labels: JUST MERGE IT!!!, priority.High

#72 Fix issues with signin navbar
  components/common/NavBar.tsx
  pages/login.tsx
Labels: JUST MERGE IT!!!, priority.High

#73 Update API and forum data
  components/common/Auth.tsx
  components/common/Login.tsx
  components/common/NavBar.tsx
  components/forum/ForumAPI.ts
  components/forum/PostList.tsx
  components/forum/PostListItem.tsx
  components/forum/PostMainItem.tsx
  docs/DeveloperGuide.md
  pages/forum/[forumId].tsx
  pages/forum/[postId].tsx
  pages/forum/index.tsx
  pages/login.tsx
  public/data/ForumData.json
Labels: JUST MERGE IT!!!, priority.High

#74 Fix hardcoded url
  components/common/Login.tsx
Labels: priority.High

#80 Minor updates to dashboard etc
  components/common/Login.tsx
  components/common/NavBar.tsx
  components/common/QuickLink.tsx
  components/landingPage/Feature.tsx
  components/landingPage/Team.tsx
  pages/404.tsx
  pages/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#82 Fixes to login flow
  components/common/Login.tsx
  components/common/NavBar.tsx
  components/common/SideBarA.tsx
  next.config.js
  pages/api/userData/index.tsx
  pages/dashboard.tsx
  pages/index.tsx
  public/cat.jpg
Labels: JUST MERGE IT!!!, priority.High

#83 Fix forum logic
  components/forum/PostListItem.tsx
  pages/forum/index.tsx
Labels: JUST MERGE IT!!!, priority.High

#84 Make Quiz with better UI
  components/dashboard/ModuleAPI.ts
  components/quiz/QuizAPI.ts
  components/quiz/QuizItem.tsx
  components/quiz/QuizList.tsx
  package.json
  pages/dashboard.tsx
  pages/quiz/index.tsx
  pages/quiz/questionMaker.tsx
  pages/quiz/quizMaker.tsx
  public/data/ModuleData.json
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#90 Minor update to styles
  components/common/NavBar.tsx
  pages/dashboard.tsx
  tailwind.config.js
Labels: JUST MERGE IT!!!, priority.High

#91 Minor update to styles
  components/common/NavBar.tsx
  pages/quiz/[quizId].tsx
Labels: JUST MERGE IT!!!

#92 add firebase and many ui updates
  .eslintrc.js
  components/common/Layout.tsx
  components/common/Login.tsx
  components/forum/ForumHome.tsx
  components/forum/ForumLayout.tsx
  components/forum/NewPost.tsx
  components/forum/PostList.tsx
  components/forum/PostMain.tsx
  package.json
  pages/_app.tsx
  pages/api/auth/[...nextauth].tsx
  pages/forum/[postId].tsx
  pages/forum/index.tsx
  pages/login.tsx
  public/data/ForumData.json
  public/data/ReplyData.json
  public/data/TestModuleData.json
  yarn.lock
Labels: JUST MERGE IT!!!, priority.High

#94 Update sidebar, footer and dashboard
  components/common/Footer.tsx
  components/common/SideBar.tsx
  components/common/SideBarA.tsx
  pages/dashboard.tsx
Labels: JUST MERGE IT!!!, priority.High
